//! Turns the repository's `rules/` tree into a table this crate compiles in.
//!
//! ADR-002 ships one statically linked executable and no runtime dependency. A
//! rule set that has to sit beside that executable is a second artefact the user
//! carries, and a binary that cannot find it scans nothing at all: the run stops
//! with `no rule directory at rules`. Embedding the tree is what makes the single
//! binary claim true rather than aspirational, and the rules are already versioned
//! with the code, so nothing about their lifecycle changes by moving them inside.
//!
//! Written as a build script rather than taken from a crate such as `include_dir`.
//! The whole job is a sorted directory walk and a generated file; CLAUDE.md's
//! answer to a new dependency for work this size is no, and a dependency here
//! would sit in the graph of a tool whose argument is that dependencies are worth
//! counting. The generated table is byte identical to the tree either way, and
//! `tests/embedded_rules.rs` is what proves it.
//!
//! Nothing below may panic. The workspace denies `clippy::panic`, and a build
//! script that panics hands the reader a backtrace where a sentence belongs, so
//! every failure prints a `cargo::error` line and exits.

use std::path::{Path, PathBuf};

fn main() {
    let manifest = match std::env::var_os("CARGO_MANIFEST_DIR") {
        Some(dir) => PathBuf::from(dir),
        None => fail("CARGO_MANIFEST_DIR is not set, so the rule tree cannot be located"),
    };
    // Two levels up from `crates/periskop-static-scanner`. Not canonicalized: on
    // Windows that produces a `\\?\` prefixed path, which `include_str!` does not
    // accept, and the components resolve perfectly well as they are.
    let rules_root = manifest.join("..").join("..").join("rules");

    let mut files: Vec<(String, PathBuf)> = Vec::new();
    if let Err(reason) = collect(&rules_root, "", &mut files) {
        fail(&reason);
    }

    // An empty table would produce a binary that loads no detector and reports a
    // clean tree to prove it, which is the defect this product exists to find
    // elsewhere. The rule tree going missing is a build failure, not a quiet
    // downgrade.
    if files.is_empty() {
        fail(&format!(
            "no rule file under {}: a binary built from an empty rule tree would scan nothing \
             and report it as clean",
            rules_root.display()
        ));
    }

    // Sorted by the path the rule is known under, so the generated table does not
    // depend on the order the filesystem handed the entries back. The report's
    // rule set digest is order independent already; this keeps the build itself
    // reproducible.
    files.sort();

    for (_, path) in &files {
        println!("cargo::rerun-if-changed={}", path.display());
    }

    let mut generated = String::from(
        "// Generated by build.rs from the repository's rules/ tree. Do not edit.\n\
         pub(crate) static EMBEDDED_RULE_FILES: &[EmbeddedRuleFile] = &[\n",
    );
    for (relative, path) in &files {
        // `{:?}` on a string emits a Rust string literal with the escaping already
        // done, which is what keeps a Windows path separator from ending the
        // literal early.
        generated.push_str(&format!(
            "    EmbeddedRuleFile {{ path: {relative:?}, text: include_str!({:?}) }},\n",
            path.to_string_lossy()
        ));
    }
    generated.push_str("];\n");

    let out_dir = match std::env::var_os("OUT_DIR") {
        Some(dir) => PathBuf::from(dir),
        None => fail("OUT_DIR is not set, so the rule table cannot be written"),
    };
    let target = out_dir.join("embedded_rules.rs");
    if let Err(e) = std::fs::write(&target, generated) {
        fail(&format!("{}: cannot be written: {e}", target.display()));
    }
}

/// Collects every `.toml` file under `dir`, keyed by its path relative to the
/// rule root.
///
/// Symbolic links to directories are not followed, which is both what the run
/// time loader does and what makes this walk terminate: a link pointing back at
/// an ancestor would otherwise hang the build rather than fail it.
fn collect(dir: &Path, prefix: &str, out: &mut Vec<(String, PathBuf)>) -> Result<(), String> {
    let entries = std::fs::read_dir(dir)
        .map_err(|e| format!("{}: the rule tree cannot be read: {e}", dir.display()))?;

    for entry in entries {
        let entry =
            entry.map_err(|e| format!("{}: an entry cannot be read: {e}", dir.display()))?;
        let path = entry.path();
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            return Err(format!(
                "{}: a file name is not valid UTF-8 and cannot be embedded",
                path.display()
            ));
        };
        let relative = if prefix.is_empty() {
            name.to_owned()
        } else {
            // Forward slashed on every platform, because this string is the
            // identity a rule is loaded and reported under and it has to read the
            // same on a Windows build as on a Linux one.
            format!("{prefix}/{name}")
        };

        let metadata = std::fs::symlink_metadata(&path)
            .map_err(|e| format!("{}: cannot be inspected: {e}", path.display()))?;
        if metadata.is_dir() {
            collect(&path, &relative, out)?;
        } else if path.extension().is_some_and(|e| e == "toml") {
            out.push((relative, path));
        }
    }

    // Every directory is watched, not only the files in it. A new rule file
    // changes its directory's own timestamp, which is what makes an added rule
    // rebuild the table instead of being silently left out of it.
    println!("cargo::rerun-if-changed={}", dir.display());
    Ok(())
}

/// Ends the build with a message rather than a backtrace.
fn fail(message: &str) -> ! {
    println!("cargo::error={message}");
    std::process::exit(1);
}
